repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        files: ^docs/
        exclude: ^docs/reference/schema
        args: ["--wrap", "keep"]
        additional_dependencies:
                  - mdformat-myst