#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Open Data Services sphinx base documentation build configuration file,
# created by sphinx-quickstart on Wed Nov  2 14:17:45 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import csv
import json
import os
import shutil

from pathlib import Path
from sphinx.util import logging
from referencing import Registry
from referencing.jsonschema import DRAFT202012

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['myst_parser',
              'sphinx_design',
              'sphinxcontrib.mermaid',
              'sphinxcontrib.opendataservices',
              'sphinxcontrib.plantuml',
              'sphinxcontrib.jsonschema',
              'sphinx_rtd_theme',
              'sphinx.ext.todo',
              'sphinx.ext.autodoc',
              'sphinx_togglebutton',]

# PlantUML path
local_plantuml_path = os.path.join(os.path.dirname(__file__), "utils", "plantuml-1.2023.10.jar")
plantuml = f"java -Djava.awt.headless=true -jar {local_plantuml_path}"

# MyST heading anchors
myst_heading_anchors = 5

linkcheck_ignore = [
    # Relative links to files created by custom code in conf.py
    r'\.\./\.\./codelists/.*\.csv$',
    # Links containing a {{version}} placeholder
    r'.*(\{\{version\}\}|%7B%7Bversion%7D%7D).*',
    # Relative links in the schema reference section
    r'\.\./(exposure|hazard|loss|resource|vulnerability).*',
    # Links that work, but are not accessible to the link checker due to robots.txt or similar
    r'^https://linux\.die\.net/man/3/libuuid$',
    r'^https://www\.sciencedirect\.com/science/article/pii/S2212420923000742$',
    r'^https://docs\.air-worldwide\.com/Database/CEDE/10\.0/webframe\.html#topic1\.html$',
    r'^https://docs\.air-worldwide\.com/Database/CEDE/10\.0/webframe\.html#topic32\.html$',
    r'^https://docs\.air-worldwide\.com/Database/CEDE/10\.0/webframe\.html#topic33\.html$',
    r'^https://gpss\.worldbank\.org/index\.php/en/node/571$'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']

source_suffix = ['.rst', '.md']

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Risk Data Library Standard'
copyright = 'Global Facility for Disaster Reduction and Recovery'
author = 'Global Facility for Disaster Reduction and Recovery'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.0'
# The full version, including alpha/beta/rc tags.
release = '1.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', '_readthedocs', 'Thumbs.db', '.DS_Store']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, Sphinx will warn about all references where the target cannot be found. Default is False. You can activate this mode temporarily using the -n command-line switch.
nitpicky = True

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = 'sphinx_rtd_theme'

html_css_files = [
    'custom.css',
    'extra.css'
]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
#
# html_title = 'Open Data Services Sphinx Base'

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
# html_logo = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
html_extra_path = ['../.temp']

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
#
# html_last_updated_fmt = None

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# html_additional_pages = {}

# If false, no module index is generated.
#
# html_domain_indices = True

# If false, no index is generated.
#
# html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr', 'zh'
#
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'sphinxdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
     # The paper size ('letterpaper' or 'a4paper').
     #
     # 'papersize': 'letterpaper',

     # The font size ('10pt', '11pt' or '12pt').
     #
     # 'pointsize': '10pt',

     # Additional stuff for the LaTeX preamble.
     #
     # 'preamble': '',

     # Latex figure (float) alignment
     #
     # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#     (master_doc, 'sphinx.tex', 'Open Data Services Sphinx Base',
#      'Open Data Services', 'manual'),
# ]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# It false, will not define \strong, \code, 	itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#
# latex_keep_old_macro_names = True

# If false, no module index is generated.
#
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
# man_pages = [
#     (master_doc, 'sphinx', 'Open Data Services Sphinx Base',
#      [author], 1)
# ]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
# texinfo_documents = [
#     (master_doc, 'sphinx', 'Open Data Services Sphinx Base',
#      author, 'sphinx', 'One line description of project.',
#      'Miscellaneous'),
# ]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False


locale_dirs = ['locale/']   # path is example but recommended.
gettext_compact = False     # optional.

togglebutton_hint = ""


def create_directory(path):
    output_dir = os.path.dirname(path)
    os.makedirs(output_dir, exist_ok=True)  

def replace_substring_in_json(file_path, search_substring, replace_string, output_path=None):
    # Read the JSON file
    with open(file_path, 'r') as file:
        data = json.load(file)

    # Recursively search and replace the substring in the JSON data
    _replace_substring_in_json(data, search_substring, replace_string)

    # Set output path
    if output_path is None:
        output_path = file_path

    # Create the directory if it does not exist
    create_directory(output_path)

    # Write the modified JSON data to the output file
    with open(output_path, 'w') as file:
        json.dump(data, file, indent=4)

def _replace_substring_in_json(data, search_substring, replace_string):
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, str):
                data[key] = value.replace(search_substring, replace_string)
            else:
                _replace_substring_in_json(value, search_substring, replace_string)
    elif isinstance(data, list):
        for i, item in enumerate(data):
            if isinstance(item, str):
                data[i] = item.replace(search_substring, replace_string)
            else:
                _replace_substring_in_json(item, search_substring, replace_string)


def dereference(schema):
    resource = DRAFT202012.create_resource(schema)

    base_uri = schema.get("$id", "")
    registry = Registry().with_resource(uri=base_uri, resource=resource)
    
    resolver = registry.resolver(base_uri=base_uri)

    def walk_and_resolve(obj):
        if isinstance(obj, dict):
            if "$ref" in obj:
                ref_value = obj["$ref"]
                try:
                    resolved = resolver.lookup(ref_value).contents
                    
                    merged = dict(resolved)
                    for key, value in obj.items():
                        if key == "$ref":
                            continue
                        if key == "properties" and "properties" in merged:
                            merged[key] = {**merged[key], **value}
                        else:
                            merged[key] = value
                    
                    return walk_and_resolve(merged)
                except Exception as e:
                    print(f"Warning: Could not resolve {ref_value}: {e}")
                    return obj

            return {k: walk_and_resolve(v) for k, v in obj.items()}
        
        elif isinstance(obj, list):
            return [walk_and_resolve(i) for i in obj]
        
        return obj

    return walk_and_resolve(schema)


def compose_all_of(schema):
    """
    Recursively merges properties defined within allOf arrays into 
    the parent object's properties.
    """

    logger = logging.getLogger(__name__)
    
    if not isinstance(schema, dict):
        return schema

    # Process all nested values first (Bottom-up recursion)
    for key, value in schema.items():
        if isinstance(value, dict):
            schema[key] = compose_all_of(value)
        elif isinstance(value, list):
            schema[key] = [compose_all_of(item) for item in value]

    # Handle allOf composition for the current object
    if "allOf" in schema:
        # Ensure base containers exist
        new_props = {}
        if "properties" not in schema:
            schema["properties"] = {}
        if "required" not in schema:
            schema["required"] = []

        for sub_schema in schema["allOf"]:
            # Gather properties
            if "properties" in sub_schema:
                for key, value in sub_schema["properties"].items():
                    if key in schema["properties"] and schema["properties"][key] != value:
                        logger.warning(f"Overwriting property {key} value {schema['properties'][key]} with value {value}")
                    new_props[key] = value
            
            # Merge required properties
            if "required" in sub_schema:
                combined_req = set(schema["required"]) | set(sub_schema["required"])
                schema["required"] = sorted(combined_req)
            
            # Inherit title
            if "title" not in schema and "title" in sub_schema:
                schema["title"] = sub_schema["title"]
            
            # Inherit description
            if  "description" not in schema and "description" in sub_schema:
                schema["description"] = sub_schema["description"]
        
        # Merge properties
        schema['properties'] = {**new_props, **schema['properties']}
        
        schema["allOf"] = [sub_schema for sub_schema in schema["allOf"] if "properties" not in sub_schema]

        if len(schema["allOf"]) == 0:
            schema.pop("allOf")
        
        # Clean up empty containers if nothing was added
        if not schema["properties"]:
            schema.pop("properties")
        if not schema["required"]:
            schema.pop("required")

    return schema


def update_conditional_codelist(schema, source_csv, output_dir, schema_def_key, property_name, include_universal=False, include_enum=False):
    """
    Refactors the derivation of hazard-specific codelists and schema definitions.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    with open(source_csv, "r") as f:
        # DictReader handles headers automatically; no next() needed
        reader = csv.DictReader(f)
        data = list(reader)

    # Group data by hazard
    hazards = {}
    for row in data:
        hazard_list = row.get('Hazard', '').split(',')
        # Remove 'Hazard' from the data that goes into the new CSV files
        clean_row = {k: v for k, v in row.items() if k != "Hazard"}
        
        for hazard in hazard_list:
            if not hazard:
                continue
            hazards.setdefault(hazard, []).append(clean_row)

    universal_data = hazards.get("universal", []) if include_universal else []
    all_of_logic = []

    for hazard, items in hazards.items():
        if hazard == 'universal':
            continue

        filename = f"{source_csv.split('/')[-1].replace('.csv', f'_{hazard.lower()}.csv')}"
        file_full_path = output_path / filename

        # Write the specific hazard CSV
        with open(file_full_path, "w") as f:
            if items:
                writer = csv.DictWriter(f, fieldnames=items[0].keys(), lineterminator='\n')
                writer.writeheader()
                writer.writerows(items)
                if include_universal:
                    writer.writerows(universal_data)

        # Build the schema 'if/then' block
        condition = {
            "if": {"properties": {"type": {"const": hazard}}},
            "then": {
                "properties": {
                    property_name: {
                        "codelist": filename
                    }
                }
            }
        }

        # Add enum if required
        if include_enum:
            condition["then"]["properties"][property_name]["enum"] = [i['Code'] for i in items]

        all_of_logic.append(condition)

    # Update the schema object
    schema['$defs'][schema_def_key]['allOf'] = all_of_logic


def remove_key(data, target_key):
    if isinstance(data, dict):
        # Create a list of keys to avoid 'RuntimeError: dictionary changed size'
        for key in list(data.keys()):
            if key == target_key:
                del data[key]
            else:
                remove_key(data[key], target_key)
    elif isinstance(data, list):
        for item in data:
            remove_key(item, target_key)
    return data


def setup(app):
    # Connect handlers to events
    app.connect('config-inited', config_inited)
    app.connect('env-before-read-docs', env_before_read_docs)
    app.connect('build-finished', build_finished)


def config_inited(app, config):
    shutil.copytree('../schema', '../.temp', dirs_exist_ok=True)

    with open("../.temp/rdls_schema.json", "r") as f:
        schema = json.load(f)

    # 1. Update IMT
    update_conditional_codelist(
        schema=schema,
        source_csv="../schema/codelists/open/imt.csv",
        output_dir="../.temp/codelists/open",
        schema_def_key="conditional_hazard_type_to_intensity_measure",
        property_name="intensity_measure",
        include_universal=True,
        include_enum=False
    )

    # 2. Update Process Type
    update_conditional_codelist(
        schema=schema,
        source_csv="../schema/codelists/closed/process_type.csv",
        output_dir="../.temp/codelists/closed",
        schema_def_key="conditional_hazard_type_to_process",
        property_name="process",
        include_universal=False,
        include_enum=True
    )

    with open("../.temp/rdls_schema.json", "w") as f:
        json.dump(schema, f, indent=2)
        f.write("\n")

    # Dereference and compose schema
    schema = dereference(schema)

    schema.pop('$defs', None)

    schema = compose_all_of(schema)

    with open('../.temp/rdls_schema_processed.json', 'w') as f:
        json.dump(schema, f, indent=2)
        f.write("\n")
    
    # Remove allOf / anyOf keywords for display in schema browser
    schema = remove_key(schema, 'allOf')
    schema = remove_key(schema, 'anyOf')

    with open('../.temp/rdls_schema_processed_browser.json', 'w') as f:
        json.dump(schema, f, indent=2)
        f.write("\n")

    rtd_version = os.getenv('READTHEDOCS_VERSION')

    # Replace {{version}} placeholders
    if rtd_version is not None:
        replace_substring_in_json('../.temp/rdls_schema.json', '{{version}}', rtd_version)
        replace_substring_in_json('../.temp/rdls_schema_processed.json', '{{version}}', rtd_version)
        replace_substring_in_json('../.temp/rdls_schema_processed_browser.json', '{{version}}', rtd_version)


def env_before_read_docs(app, env, docnames):
    create_directory('_readthedocs/html/')
    shutil.copytree('../.temp', '_readthedocs/html', dirs_exist_ok=True)

def build_finished(app, exception):
    shutil.rmtree('../.temp')
