name: Link Check

on:
  push:
  pull_request:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Sphinx Linkcheck
        working-directory: ./docs
        run: |
          sphinx-build -b linkcheck -q . _readthedocs/html